### ISSUE TITLE
GuSTO SCP iteration failed to find an optimal solution

### ISSUE THREAD

**Issue by markcsie** [StanfordASL/GuSTO.jl#4]
Hi, I tried running your examples with `SCSSolver`. It failed to find solutions for every example. Do you have any ideas why it fails? Is there any parameter that I should change in order to make it work? Would it be solved if switching to `Gurobi` or `Mosek` solvers?

SCS log:
SCS v2.0.2 - Splitting Conic Solver
(c) Brendan O'Donoghue, Stanford University, 2012-2017

Lin-sys: sparse-indirect, nnz in A = 2650, CG tol ~ 1/iter^(2.00)
eps = 1.00e-05, alpha = 1.50, max_iters = 5000, normalize = 1, scale = 1.00
acceleration_lookback = 20, rho_x = 1.00e-03
Variables n = 790, constraints m = 1694
Cones:	primal zero / dual free vars: 217
	linear vars: 577
	soc vars: 900, soc blks: 251
Setup time: 4.72e-04s

 Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
   0| 2.16e+21  6.53e+20  9.68e-01 -8.15e+22 -1.33e+21  4.06e+22  6.94e-04 
   100| 4.54e-03  5.00e-02  6.15e-03  1.24e+00  1.22e+00  2.58e-14  2.79e-02 
   200| 2.50e-03  2.98e-02  8.36e-03  1.20e+00  1.23e+00  3.99e-14  5.47e-02 
   300| 2.43e-03  2.65e-02  1.16e-02  1.20e+00  1.24e+00  7.35e-14  8.21e-02 
   400| 1.71e-03  1.78e-02  7.96e-04  1.23e+00  1.23e+00  1.28e-14  1.10e-01 
   500| 1.04e-03  1.23e-02  7.72e-04  1.23e+00  1.23e+00  3.88e-14  1.38e-01 
   600| 8.34e-04  1.00e-02  4.50e-03  1.22e+00  1.24e+00  1.51e-15  1.66e-01 
   700| 5.19e-04  6.42e-03  2.16e-03  1.24e+00  1.23e+00  1.54e-14  1.94e-01 
   800| 3.07e-04  3.73e-03  1.70e-03  1.23e+00  1.23e+00  1.49e-14  2.21e-01 
   900| 2.36e-04  2.45e-03  7.74e-04  1.23e+00  1.23e+00  1.44e-14  2.49e-01 
  1000| 7.44e-04  7.77e-03  1.64e-03  1.22e+00  1.23e+00  6.94e-15  2.76e-01 
  1100| 4.05e-04  4.89e-03  5.20e-04  1.23e+00  1.23e+00  7.93e-14  3.05e-01 
  1200| 2.47e-04  3.31e-03  2.53e-04  1.23e+00  1.23e+00  1.52e-14  3.33e-01 
  1300| 3.29e-04  4.00e-03  2.52e-04  1.23e+00  1.23e+00  7.24e-14  3.61e-01 
  1400| 5.08e-04  4.49e-03  1.64e-03  1.22e+00  1.23e+00  1.17e-13  3.89e-01 
  1500| 3.06e-04  3.59e-03  2.65e-04  1.23e+00  1.23e+00  3.39e-14  4.18e-01 
  1600| 2.96e-04  3.36e-03  1.23e-03  1.24e+00  1.23e+00  2.92e-15  4.47e-01 
  1700| 2.49e-04  2.50e-03  2.82e-04  1.23e+00  1.23e+00  5.15e-14  4.76e-01 
  1800| 1.51e-04  1.71e-03  6.03e-04  1.23e+00  1.23e+00  6.79e-14  5.05e-01 
  1900| 2.47e-04  3.28e-03  1.04e-05  1.23e+00  1.23e+00  4.77e-14  5.33e-01 
  2000| 2.14e-04  2.55e-03  2.57e-05  1.23e+00  1.23e+00  6.79e-15  5.63e-01 
  2100| 2.55e-04  2.72e-03  8.18e-04  1.23e+00  1.23e+00  6.45e-14  5.92e-01 
  2200| 3.35e-04  4.04e-03  7.36e-04  1.23e+00  1.23e+00  4.33e-14  6.21e-01 
  2300| 4.27e-04  4.51e-03  9.30e-04  1.23e+00  1.23e+00  1.11e-14  6.51e-01 
  2400| 1.67e-04  1.74e-03  3.86e-04  1.23e+00  1.23e+00  8.41e-15  6.80e-01 
  2500| 3.48e-04  4.26e-03  5.67e-04  1.23e+00  1.23e+00  1.04e-14  7.10e-01 
  2600| 3.02e-04  3.45e-03  9.10e-04  1.23e+00  1.23e+00  3.54e-14  7.39e-01 
  2700| 1.54e-04  1.84e-03  2.71e-04  1.23e+00  1.23e+00  2.09e-14  7.69e-01 
  2800| 1.87e-04  2.05e-03  6.29e-04  1.23e+00  1.23e+00  6.96e-14  7.98e-01 
  2900| 2.77e-04  2.98e-03  6.74e-04  1.23e+00  1.23e+00  2.69e-14  8.28e-01 
  3000| 3.44e-04  3.86e-03  4.80e-04  1.23e+00  1.23e+00  8.60e-14  8.57e-01 
  3100| 2.44e-04  3.17e-03  8.07e-04  1.23e+00  1.23e+00  1.08e-13  8.87e-01 
  3200| 2.73e-04  3.74e-03  1.13e-03  1.23e+00  1.23e+00  1.35e-13  9.17e-01 
  3300| 1.70e-04  1.99e-03  2.65e-04  1.23e+00  1.23e+00  6.66e-14  9.47e-01 
  3400| 1.72e-04  1.66e-03  7.77e-05  1.23e+00  1.23e+00  4.30e-14  9.77e-01 
  3500| 3.09e-04  3.51e-03  1.76e-03  1.23e+00  1.23e+00  5.21e-14  1.01e+00 
  3600| 2.90e-04  3.62e-03  1.41e-03  1.23e+00  1.23e+00  2.64e-14  1.04e+00 
  3700| 3.23e-04  3.46e-03  2.25e-04  1.23e+00  1.23e+00  6.35e-14  1.07e+00 
  3800| 3.21e-04  3.77e-03  1.20e-03  1.24e+00  1.23e+00  2.70e-14  1.10e+00 
  3900| 2.02e-04  2.60e-03  8.68e-04  1.23e+00  1.23e+00  1.39e-14  1.13e+00 
  4000| 1.95e-04  2.29e-03  2.05e-04  1.23e+00  1.23e+00  4.23e-15  1.16e+00 
  4100| 4.44e-04  4.94e-03  7.35e-05  1.23e+00  1.23e+00  8.00e-16  1.19e+00 
  4200| 4.96e-04  5.88e-03  1.13e-03  1.24e+00  1.23e+00  2.80e-14  1.22e+00 
  4300| 4.46e-04  4.67e-03  1.25e-03  1.23e+00  1.23e+00  2.17e-14  1.25e+00 
  4400| 1.90e-04  2.10e-03  6.94e-04  1.23e+00  1.23e+00  7.13e-15  1.28e+00 
  4500| 1.60e-04  1.80e-03  1.40e-03  1.23e+00  1.23e+00  5.94e-14  1.31e+00 
  4600| 1.73e-04  2.16e-03  9.64e-04  1.23e+00  1.23e+00  3.09e-15  1.34e+00 
  4700| 2.14e-04  2.37e-03  4.39e-04  1.23e+00  1.23e+00  3.64e-14  1.37e+00 
  4800| 2.61e-04  2.82e-03  4.63e-04  1.23e+00  1.23e+00  5.34e-14  1.40e+00 
  4900| 2.44e-04  2.63e-03  6.55e-04  1.23e+00  1.23e+00  3.53e-15  1.44e+00 
  5000| 2.17e-04  2.49e-03  4.30e-04  1.23e+00  1.23e+00  4.81e-14  1.47e+00 

Status: Solved/Inaccurate
Hit max_iters, solution may be inaccurate
Timing: Solve time: 1.47e+00s
	Lin-sys: avg # CG iterations: 9.81, avg solve time: 1.22e-04s
	Cones: avg projection time: 3.41e-06s
	Acceleration: avg step time: 1.32e-04s

Error metrics:
dist(s, K) = 1.1324e-07, dist(y, K*) = 2.6577e-07, s'y/|s||y| = -2.8386e-10
primal res: |Ax + s - b|_2 / (1 + |b|_2) = 2.1736e-04
dual res:   |A'y + c|_2 / (1 + |c|_2) = 2.4913e-03
rel gap:    |c'x + b'y| / (1 + |c'x| + |b'y|) = 4.3017e-04

c'x = 1.2326, -b'y = 1.2341

WARNING: Problem status UnknownError; solution may be inaccurate.
WARNING: GuSTO SCP iteration failed to find an optimal solution

**Comment by ambyld** [comment]
Hi, thank you for the question. One possible issue with the examples is that SCS requires a linear objective function, and all of the examples currently use a quadratic cost based on control effort. I'm not sure what linear function of the control trajectory can be used as a useful objective.

Did you change the cost functions in order to use SCS? If it is an issue with the new cost functions, it may not be helpful to retry the modified examples using Gurobi or Mosek.

**Comment by markcsie** [comment]
No, I didn't change the cost function, so it's still the quadratic cost. Is Gurobi or Mosek able to solve the quadratic cost optimization problem?

**Comment by ambyld** [comment]
I just tested freeflyerSE2.ipynb using Gurobi and Ipopt, and they are both able to solve. Trying with Mosek gave the error `The solver does not support an objective function of type MathOptInterface.ScalarQuadraticFunction{Float64}.` so Gurobi and Ipopt may be your best bet for now. 

By the way, we recently merged the updated version of GuSTO.jl running in Julia 1.X with the new version of JuMP.jl into master, so it may be worth trying that if you haven't already.

**Comment by markcsie** [comment]
Thank you very much for the prompt reply and updates.
I tried switching to Julia 1.1.1 with the updated GuSTO, however many problems appeared.
I am on Ubuntu 16.04.
1. Julia crashed while `using FillArrays` or `using LinearAlgebra`
julia> using GuSTO
[ Info: Precompiling GuSTO [ceb88251-baee-58f1-80cf-3a3b27eec344]
┌ Warning: Package Base does not have BulletCollision in its dependencies:
│ - If you have Base checked out for development and have
│   added BulletCollision as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with Base
└ Loading BulletCollision into Base from project dependency, future warnings for Base are suppressed.
┌ Warning: Module BulletCollision with build ID 15880324299667 is missing from the cache.
│ This may mean BulletCollision [b3564421-7037-56b3-90f4-5b7f54e2ead3] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:947
julia: malloc.c:2868: mremap_chunk: Assertion `((size + offset) & (GLRO (dl_pagesize) - 1)) == 0' failed.

signal (6): Aborted
in expression starting at /home/markma/.julia/packages/GuSTO/XOYmb/src/GuSTO.jl:27
raise at /build/glibc-Cl5G7W/glibc-2.23/signal/../sysdeps/unix/sysv/linux/raise.c:54
abort at /build/glibc-Cl5G7W/glibc-2.23/stdlib/abort.c:89
__malloc_assert at /build/glibc-Cl5G7W/glibc-2.23/malloc/malloc.c:301
mremap_chunk at /build/glibc-Cl5G7W/glibc-2.23/malloc/malloc.c:2868
__libc_realloc at /build/glibc-Cl5G7W/glibc-2.23/malloc/malloc.c:3025
arraylist_grow at /buildworker/worker/package_linux64/build/src/support/arraylist.c:58 [inlined]
arraylist_push at /buildworker/worker/package_linux64/build/src/support/arraylist.c:69
jl_module_using at /buildworker/worker/package_linux64/build/src/module.c:446
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:642
jl_parse_eval_all at /buildworker/worker/package_linux64/build/src/ast.c:883
jl_load at /buildworker/worker/package_linux64/build/src/toplevel.c:826
include at ./boot.jl:326 [inlined]
include_relative at ./loading.jl:1038
_require at ./loading.jl:986
require at ./loading.jl:858
require at ./loading.jl:853
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2197
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1571 [inlined]
call_require at /buildworker/worker/package_linux64/build/src/toplevel.c:397 [inlined]
eval_import_path at /buildworker/worker/package_linux64/build/src/toplevel.c:432
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:630
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/toplevel.c:793
eval at ./boot.jl:328
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2197
eval_user_input at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/REPL/src/REPL.jl:85
macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/REPL/src/REPL.jl:117 [inlined]
#26 at ./task.jl:259
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2197
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1571 [inlined]
start_task at /buildworker/worker/package_linux64/build/src/task.c:572
unknown function (ip: 0xffffffffffffffff)
Allocations: 133391985 (Pool: 133379551; Big: 12434); GC: 175
Aborted (core dumped)

Strangely, both `using FillArrays` and `using LinearAlgebra` work fine if importing in the REPL directly.

2. `ERROR: LoadError: UndefVarError: include not defined`
Stacktrace:
 [1] top-level scope at none:0
 [2] include at ./boot.jl:326 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1038
 [4] _require(::Base.PkgId) at ./loading.jl:986
 [5] require(::Base.PkgId) at ./loading.jl:858
 [6] require(::Module, ::Symbol) at ./loading.jl:853
in expression starting at /home/markma/.julia/packages/GuSTO/XOYmb/src/GuSTO.jl:33

Tried change it to `Base.include(Main, "types.jl")`, but still I need to add `using DataStructures, Convex, JuMP` to fix the import issue. 
How come you don't have this problem? Which Julia version do you use or recommend?

**Comment by markcsie** [comment]
Ok, I saw the `freeflyerSE2`, you changed `using GuSTO` to `include("../src/GuSTO.jl")`. 
The example works for me now, but I am still curious about the issue I was having. Do you know the difference between `using GuSTO` and `include("../src/GuSTO.jl")`?

**Comment by ambyld** [comment]
Yes, the reason we use `include("../src/GuSTO.jl")` is because in GuSTO.jl, the lines making GuSTO a module are currently commented out, which has been helpful while developing the package. Apologies for the inconvenience this has caused. We have been busy with other projects recently, but we will be officially registering GuSTO and its associated packages soon and at that point this will be made a module again and the installation process will be improved.

**Comment by markcsie** [comment]
No worries, thank you for the answer.
