### ISSUE TITLE
Trust Region Computation of Obstacle Avoidance

### ISSUE THREAD

**Issue by markcsie** [StanfordASL/GuSTO.jl#6]
In `freeflyer_se2.jl`
```
# TODO(ambyld): Update for arm
  for k in 1:N
    r0 = get_workspace_location(traj, SCPP, k)
    r = get_workspace_location(traj_prev, SCPP, k)
    for (rb_idx, body_point) in enumerate(env_.convex_robot_components)
      for (env_idx,convex_env_component) in enumerate(env_.convex_env_components)
        dist,xbody,xobs = BulletCollision.distance(env_,rb_idx,r0,env_idx)
        nhat = dist > 0 ?
          (xbody-xobs)./norm(xbody-xobs) :
          (xobs-xbody)./norm(xobs-xbody) 
        linearized = clearance - (dist + nhat'*(r-r0))
        dist,xbody,xobs = BulletCollision.distance(env_,rb_idx,r,env_idx)
        num += abs((clearance-dist) - linearized) 
        den += abs(linearized) 
      end
    end
  end
```
For this piece of code, my understanding is that it's calculating the approximation error of the linearization.
Why is `r0` from the optimized trajectory instead of previous trajectory?

**Comment by acauligi** [comment]
The trust region ratio definition here is computed as defined in Eq. 5 in this [paper](https://arxiv.org/pdf/1903.00155.pdf).

The variable naming could be less confusing here, but the first `dist,xbody,xobs` computation uses `r0` and the second computation does use `r`. The first `dist` is used in the linearized constraint evaluation, i.e. what does the signed distance linearization about the previous trajectory evaluate to when the optimized value is plugged in: `linearized = clearance - (dist + nhat'*(r-r0))` (where `r-r0` corresponds to evaluating the optimized trajectory around the previous iteration.)

This `linearized` value is then subtracted from the true signed distance value at the previous trajectory in the final line: `abs((clearance-dist) - linearized)`.

**Comment by markcsie** [comment]
That is what I interpreted the piece of code too.
So shouldn't  
```
r0 = get_workspace_location(traj_prev, SCPP, k)
r = get_workspace_location(traj, SCPP, k)
```
be more correct instead of
```
r0 = get_workspace_location(traj, SCPP, k)
r = get_workspace_location(traj_prev, SCPP, k)
```
in your source code?
Was it a typo?

**Comment by acauligi** [comment]
Yes, that does seem to be a typo, thanks for catching that! I'll go ahead and update it across the different dynamics/*.jl files.

**Comment by markcsie** [comment]
No problem, feel free to close the issue once you finish updating.

**Comment by acauligi** [comment]
[Fixed here.](https://github.com/StanfordASL/GuSTO.jl/commit/4de33f797a30130e0af928fc57495f1e31119dc0)
