### ISSUE TITLE
Questions regarding to optimization solvers

### ISSUE THREAD

**Issue by markcsie** [StanfordASL/GuSTO.jl#7]
It seems like GuSTO essentially approaches the full optimal control problem by solving Quadratic Programmings sequentially. 
If that's the case, is it an overkill to use IPOPT to solve the QP? or is it essentially the same?
Have you tried other solvers to solve the QP?
If using other solvers tailored for QP, would it solve the problem more efficiently compared to IPOPT?
In your research, have you tried manage to solve the full non-linear optimal control problem with any NLP solver and compare the results? (I guess it would be less efficient and less robust, but I am still curious about the analysis.)

Excuse me for asking so many questions, but I am really interested in your work. I am not an expert in this field so if I misunderstand something please feel free to point me out.

**Comment by acauligi** [comment]
Sorry for the delay in responding. Generally, most of the optimal control problems we consider in this problem are roughly at the hierarchy of non-convex QCQP's, where the non-convexity is from the obstacle avoidance inequality and nonlinear dynamics equality constraints.

The short answer to your question of whether we're tried using a non-convex solver (e.g. Ipopt, Snopt) to solve the original non-convex problem at one go is no.

For the convexified subproblems generated at each iteration, we use convex NLP solvers such as Gurobi or Mosek, but Ipopt or Snopt could be used as well depending on the nature of the subproblem (i.e. smooth, LP vs QP, etc.)
